const all_answers = [
  "In the part of Montreal where she was elected.",
  "The party with the most elected representatives is invited by the Governor General to become the party in power.",
  "More than 600,000.",
  "10",
  "Equality of women and men",
  'From "Kanata", the Huron-Iroquois word for village.',
  "Volunteer.",
  "In the Parliament of Canada.",
  "O Canada! Our home and native land!",
  "Elected by Canadian citizens.",
  "Senators are appointed by the Governor General on the advice of the Prime Minister.",
  "Approval by a majority in the House of Commons and Senate and finally the Governor General.",
  "By the Prime Minister",
  "Ordinarily, the party with the most elected representatives becomes the party in power. The leader of this party becomes the Prime Minister.",
  "The leader of the party with the most elected representatives becomes the Prime Minister.",
  "Yes, if you feel the need to.",
  "Everyone is innocent until proven guilty",
  "The Quiet Revolution.",
  "Service.",
  "Central Canada.",
  "Conservative (O'Toole), NDP (Singh), Liberal (Trudeau), Bloc Quebecois (Blanchet), Green Party (Paul)",
  "Obeying the law, taking responsibility for oneself and one's family, helping others in the community, voting in elections, serving on a jury, protecting and enjoying our heritage and environment.",
  "Atlantic, Central, Prairie, West Coast, and North",
  "Mobility rights, Multiculturalism, and Aboriginal Peoples' rights.",
  "Freedom of conscience and religion, and Freedom of association.",
  "Canadian Charter of Rights and Freedoms and Magna Carta (the Great Charter of Freedoms).",
  "National defence and foreign policy.",
  "Health and Education",
  "April 1st, 1999",
  "Ontario.",
  "From sea to sea.",
  "Getting a job, taking care of one's family and working hard in keeping with one's abilities.",
  "Alberta (Edmonton), Saskatchewan (Regina) and Manitoba (Winnipeg).",
  "Ontario (Toronto) and Quebec (Quebec City).",
  "Newfoundland and Labrador (St. John's), Nova Scotia (Halifax), New Brunswick (Fredericton) and Prince Edward Island (Charlottetown).",
  "Yukon Territory (Whitehorse), Northwest Territories (Yellowknife), and Nunavut (Iqaluit).",
  "Federal, Provincial and Territorial, Municipal (local).",
  "First Nations, Métis and Inuit.",
  "Natural resources, manufacturing and services.",
  "The Sovereign, the House of Commons and the Senate.",
  "English and French.",
  "United States of America.",
  "Unity.",
  "They worked together to establish a new country, the Dominion of Canada",
  "A Bill.",
  "Lieutenant-Governor.",
  'An "X".',
  "Joining of provinces to make a new country.",
  "Canada's Head of State is a hereditary Sovereign (Queen or King) who reigns in accordance with the Constitution.",
  "No one can watch your vote and no one should look at how you voted",
  "White with a red border on each end and a red maple leaf in the centre.",
  "The ministers of the Crown must have the support of a majority of the elected representatives in order to govern.",
  '"The people" in the Inuktitut language.',
  "The British defeated the French marking the end of France's empire in America",
  "A person who speaks French as their first language",
  "St. Lawrence River",
  "When the party in power holds at least half of the seats in the House of Commons.",
  "A form that tells you when and where to vote.",
  "Hockey.",
  "Parliamentary government.",
  "Men and women are equal under the law.",
  "Race-based entry fee charged for Chinese entering Canada.",
  "Ottawa.",
  "The Sovereign is the guardian of Constitutional freedoms, the Prime Minister selects the Cabinet ministers and is responsible for operations and policy of government.",
  "Federal.",
  "The Supreme Court of Canada",
  "Victoria Cross.",
  "Catholic.",
  "To remember the sacrifice of Canadians who have served or died in wars up to the present day.",
  "Richard Wagner.",
  "Justin Trudeau (Liberal Party).",
  "God Save the Queen (or King).",
  "To settle disputes.",
  "To oppose or try to improve government proposals.",
  "Insulin has saved 16 million lives worldwide.",
  "The Canadian Charter of Rights and Freedoms.",
  "65%.",
  "Call Elections Canada or visit their website.",
  "O Canada.",
  "Atlantic, Arctic and Pacific.",
  "An anti-slavery network that helped thousands of slaves escape the United States and settle in Canada",
  "Canadians made a significant contribution to the defeat of Nazism and Fascism in Europe during the Second World War.",
  "The effort by women to achieve the right to vote.",
  "Pledge allegiance to the Queen, observe the laws of Canada and fulfil the duties of a Canadian.",
  "1949",
  "1867.",
  "No one.",
  "1867.",
  "1982.",
  "We celebrate the anniversary of Confederation July 1st of each year.",
  "November 11th.",
  "On the third Monday in October every four years following the most recent general election.",
  "Go to the voting station with your voter's card and ID, mark an X next to your chosen candidate, fold the ballot and present it to the poll officials who will tear off the ballot number and give you the ballot to deposit in the box",
  "Between Ontario and the United States",
  "Ottawa.",
  "Quebec.",
  "Second",
  "The Constitutional Act of 1791.",
  "The beaver.",
  "United States of America.",
  "Liberal Party.",
  "Dictatorship.",
  "The USA invaded Canada and was defeated, which ensured that Canada would remain independent of the United States.",
  "The schools were welcomed by the Aboriginal people.",
  "The party with the second most MPs.",
  "The Conservative Party.",
  "The Port of Vancouver",
  "Newfoundland and Labrador",
  "Prince Edward Island.",
  "Quebec",
  "New Brunswick.",
  "The Province of Canada",
  "Manitoba",
  "Quebec",
  "Northern Territories.",
  "Central Canada.",
  "Prairie provinces.",
  "Canada, Mexico and the United States.",
  "Newfoundland.",
  "The first people to live in Canada",
  "The descendants of French colonists who began settling in what are now the Maritime provinces in 1604.",
  "Aboriginal, French and British.",
  "A distinct people of mixed Aboriginal and European ancestry.",
  "People of Quebec.",
  "A candidate they want to represent them in Parliament.",
  "Everyone who lives in his or her electoral district.",
  "Chinese railroad workers.",
  "Any Canadian citizen who is at least 18 years old.",
  "A Canadian citizen, 18 years or older, and on voters' list.",
  "Band chiefs and councillors.",
  "Her Majesty Queen Elizabeth II.",
  "Louis Riel",
  "Canada's greatest soldier in the First World War.",
  "The Prime Minister",
  "Erin O'Toole",
  "Governor General of Canada.",
  "Louis Riel",
  "Sir George-Étienne Cartier",
  "A champion of democracy and French language rights and the first leader of a responsible government in the Canadas.",
  "A great frontier hero, Mounted Policeman and soldier of the Queen.",
  "Sir Louis-Hippolyte La Fontaine.",
  "Sir John A. Macdonald.",
  "Settlers who came to Canada from the United States during the American Revolution.",
  "Montreal-based traders who travelled by canoe",
  "Canadian Corps secured its reputation for valour and bravery.",
  "It enhances our economy and raises our standard of living.",
  "Honourable J. Michel Doyon",
  "Edmonton.",
  "Rachel Notley.",
  "Salma Lakhani.",
  "Premier Jason Kenney.",
  "United Conservative Party",
  "Oil, agriculture, and forestry.",
  "Richmond has two federal electoral districts: Richmond Centre and Steveston-Richmond East",
  "Alice Wong (Conservative), Kenny Chiu (Conservative)",
  "Teresa Wat (Richmond North Centre), Henry Yao (Richmond South Centre), Kelly Greene(Richmond-Steveston), Aman Singh (Richmond-Queensborough).",
  "Harold Steves, Chak Au and Carol Day",
  "Victoria.",
  "Shirley Bond",
  "Janet Austin",
  "Mayor Malcolm Brodie",
  "Premier John Horgan",
  "New Democratic Party",
  "Forests, fish and water.",
  "Billions of dollars in trade goods are handled through the Port of Vancouver.",
  "Winnipeg",
  "Wab Kinew",
  "Honourable Janice Filmon",
  "Premier Brian Pallister",
  "Agriculture, mining and hydro-electric power generation",
  "Progressive Conservative",
  "Fredericton",
  "Roger Melanson",
  "Honourable Brenda Murphy",
  "Premier Blaine Higgs",
  "Forestry, agriculture and mining",
  "Progressive Conservative",
  "St. John's",
  "Ches Crosbie",
  "Honourable Judy May Foote",
  "Premier Andrew Furey",
  "Fisheries, oil and gas extraction",
  "Liberal Party",
  "Halifax",
  "Tim Houston",
  "Honourable Arthur J. LeBlanc",
  "Premier Iain Rankin",
  "Coal mining, forestry and agriculture",
  "Liberal",
  "Yellowknife",
  "Honourable Margaret Thom",
  "None",
  "Premier Caroline Cochrane",
  "Governed by consensus",
  "Iqaluit",
  "Honourable Nellie Taptaqut Kusugak",
  "None",
  "Premier Joe Savikataaq",
  "Governed by consensus",
  "Toronto",
  "Andrea Horwath",
  "Elizabeth Dowdeswell",
  "Premier Doug Ford",
  "Mining, tourism, automobile manufacturing",
  "Progressive Conservative Party",
  "Rod Phillips, Todd Smith, Michael Coteau",
  "David McGuinty, Mona Fortier, Catherine McKenna",
  "Charlottetown",
  "Peter Bevan-Baker",
  "Honourable Antoinette Perry",
  "Premier Dennis King",
  "Progressive Conservative",
  "Quebec City",
  "Dominique Anglade",
  "Premier Francois Legault",
  "Pulp and paper, forestry and hydro-electric power",
  "Coalition Avenir Québec",
  "Regina",
  "Ryan Meili",
  "Honourable Russ Mirasty",
  "Premier Scott Moe",
  "Farming, mining and natural gas",
  "Saskatchewan Party",
  "Whitehorse",
  "Honourable Angélique Bernard",
  "Stacey Hassard",
  "Premier Sandy Silver",
  "Liberal",
];
export default all_answers;
