const all_questions = [
  {
    id: 1,
    question: "A Member of Parliament from Montreal announces that she will spend her weekend in her electoral district. This means she would be:",
    answers: [],
    correnctAnswer: "In the part of Montreal where she was elected.",
    image: "",
    explanation: "",
  },
  {
    id: 2,
    question: "After a federal election, which party forms the new government?",
    answers: [],
    correnctAnswer: "The party with the most elected representatives is invited by the Governor General to become the party in power.",
    image: "",
    explanation: "",
  },
  { id: 3, question: "Approximately how many Canadians served in the First World War?", answers: [], correnctAnswer: "More than 600,000.", image: "", explanation: "" },
  { id: 4, question: "Canada has three territories and how many provinces?", answers: [], correnctAnswer: "10", image: "", explanation: "" },
  {
    id: 5,
    question: "Fatima is a new immigrant in Canada. What law allows her to take a job at par with a man?",
    answers: [],
    correnctAnswer: "Equality of women and men",
    image: "",
    explanation: "",
  },
  {
    id: 6,
    question: "From where does the name “Canada” come from?",
    answers: [],
    correnctAnswer: 'From "Kanata", the Huron-Iroquois word for village.',
    image: "",
    explanation: "",
  },
  {
    id: 7,
    question: "Give an example of how you can show responsibility by participating in your community.",
    answers: [],
    correnctAnswer: "Volunteer.",
    image: "",
    explanation: "",
  },
  {
    id: 8,
    question: "Give an example of where English and French have equal status in Canada.",
    answers: [],
    correnctAnswer: "In the Parliament of Canada.",
    image: "",
    explanation: "",
  },
  { id: 9, question: "Give the first line of Canada’s national anthem?", answers: [], correnctAnswer: "O Canada! Our home and native land!", image: "", explanation: "" },
  { id: 10, question: "10. How are Members of Parliament chosen?", answers: [], correnctAnswer: "Elected by Canadian citizens.", image: "", explanation: "" },
  {
    id: 11,
    question: "How are Senators chosen?",
    answers: [],
    correnctAnswer: "Senators are appointed by the Governor General on the advice of the Prime Minister.",
    image: "",
    explanation: "",
  },
  {
    id: 12,
    question: "How does a bill become a law?",
    answers: [],
    correnctAnswer: "Approval by a majority in the House of Commons and Senate and finally the Governor General.",
    image: "",
    explanation: "",
  },
  { id: 13, question: "How is a Cabinet Minister chosen?", answers: [], correnctAnswer: "By the Prime Minister", image: "", explanation: "" },
  {
    id: 14,
    question: "How is the government formed after a federal election?",
    answers: [],
    correnctAnswer: "Ordinarily, the party with the most elected representatives becomes the party in power. The leader of this party becomes the Prime Minister.",
    image: "",
    explanation: "",
  },
  {
    id: 15,
    question: "How is the Prime Minister chosen?",
    answers: [],
    correnctAnswer: "The leader of the party with the most elected representatives becomes the Prime Minister.",
    image: "",
    explanation: "",
  },
  {
    id: 16,
    question: "In Canada, are you allowed to question the police about their service or conduct?",
    answers: [],
    correnctAnswer: "Yes, if you feel the need to.",
    image: "",
    explanation: "",
  },
  {
    id: 17,
    question: "In Canada’s justice system what does “presumption of innocence” mean?",
    answers: [],
    correnctAnswer: "Everyone is innocent until proven guilty",
    image: "",
    explanation: "",
  },
  {
    id: 18,
    question: "In the 1960s, Quebec experienced an era of rapid change. What is this called?",
    answers: [],
    correnctAnswer: "The Quiet Revolution.",
    image: "",
    explanation: "",
  },
  { id: 19, question: "In what industry do most Canadians work?", answers: [], correnctAnswer: "Service.", image: "", explanation: "" },
  { id: 20, question: "In which region do more than half the people in Canada live?", answers: [], correnctAnswer: "Central Canada.", image: "", explanation: "" },
  {
    id: 21,
    question: "Name all the federal political parties in the House of Commons and their leaders",
    answers: [],
    correnctAnswer: "Conservative (O'Toole), NDP (Singh), Liberal (Trudeau), Bloc Quebecois (Blanchet), Green Party (Paul)",
    image: "",
    explanation: "",
  },
  {
    id: 22,
    question: "Name six responsibilities of citizenship.",
    answers: [],
    correnctAnswer:
      "Obeying the law, taking responsibility for oneself and one's family, helping others in the community, voting in elections, serving on a jury, protecting and enjoying our heritage and environment.",
    image: "",
    explanation: "",
  },
  { id: 23, question: "Name the five regions of Canada", answers: [], correnctAnswer: "Atlantic, Central, Prairie, West Coast, and North", image: "", explanation: "" },
  {
    id: 24,
    question: "Name three additional rights protected by the Canadian Charter of Rights and Freedoms",
    answers: [],
    correnctAnswer: "Mobility rights, Multiculturalism, and Aboriginal Peoples' rights.",
    image: "",
    explanation: "",
  },
  {
    id: 25,
    question: "Name two fundamental freedoms protected by the Canadian Charter of Rights and Freedoms.",
    answers: [],
    correnctAnswer: "Freedom of conscience and religion, and Freedom of association.",
    image: "",
    explanation: "",
  },
  {
    id: 26,
    question: "Name two key documents that contain our rights and freedoms.",
    answers: [],
    correnctAnswer: "Canadian Charter of Rights and Freedoms and Magna Carta (the Great Charter of Freedoms).",
    image: "",
    explanation: "",
  },
  { id: 27, question: "Name two responsibilities of the federal government.", answers: [], correnctAnswer: "National defence and foreign policy.", image: "", explanation: "" },
  { id: 28, question: "Name two responsibilities of the provincial and territorial government.", answers: [], correnctAnswer: "Health and Education", image: "", explanation: "" },
  { id: 29, question: "On what date did Nunavut become a territory?", answers: [], correnctAnswer: "April 1st, 1999", image: "", explanation: "" },
  { id: 30, question: "One third of all Canadians live in which province?", answers: [], correnctAnswer: "Ontario.", image: "", explanation: "" },
  { id: 31, question: "The Canadian Coat of Arms and motto is “A Mari Usque Ad Mare.” This means:", answers: [], correnctAnswer: "From sea to sea.", image: "", explanation: "" },
  {
    id: 32,
    question: "What are some examples of taking responsibility for yourself and your family?",
    answers: [],
    correnctAnswer: "Getting a job, taking care of one's family and working hard in keeping with one's abilities.",
    image: "",
    explanation: "",
  },
  {
    id: 33,
    question: "What are the Prairie provinces and their capital cities?",
    answers: [],
    correnctAnswer: "Alberta (Edmonton), Saskatchewan (Regina) and Manitoba (Winnipeg).",
    image: "",
    explanation: "",
  },
  {
    id: 34,
    question: "What are the provinces of Central Canada and their capital cities?",
    answers: [],
    correnctAnswer: "Ontario (Toronto) and Quebec (Quebec City).",
    image: "",
    explanation: "",
  },
  {
    id: 35,
    question: "What are the provinces of the Atlantic region and their capital cities?",
    answers: [],
    correnctAnswer: "Newfoundland and Labrador (St. John's), Nova Scotia (Halifax), New Brunswick (Fredericton) and Prince Edward Island (Charlottetown).",
    image: "",
    explanation: "",
  },
  {
    id: 36,
    question: "What are the territories of Northern Canada and their capital cities?",
    answers: [],
    correnctAnswer: "Yukon Territory (Whitehorse), Northwest Territories (Yellowknife), and Nunavut (Iqaluit).",
    image: "",
    explanation: "",
  },
  {
    id: 37,
    question: "What are the three levels of government in Canada?",
    answers: [],
    correnctAnswer: "Federal, Provincial and Territorial, Municipal (local).",
    image: "",
    explanation: "",
  },
  { id: 38, question: "What are the three main groups of Aboriginal peoples?", answers: [], correnctAnswer: "First Nations, Métis and Inuit.", image: "", explanation: "" },
  {
    id: 39,
    question: "What are the three main types of industry in Canada?",
    answers: [],
    correnctAnswer: "Natural resources, manufacturing and services.",
    image: "",
    explanation: "",
  },
  { id: 40, question: "What are the three parts of Parliament?", answers: [], correnctAnswer: "The Sovereign, the House of Commons and the Senate.", image: "", explanation: "" },
  { id: 41, question: "What are the two official languages of Canada?", answers: [], correnctAnswer: "English and French.", image: "", explanation: "" },
  { id: 42, question: "What country is Canada’s largest trading partner?", answers: [], correnctAnswer: "United States of America.", image: "", explanation: "" },
  { id: 43, question: "What did the Canadian Pacific Railway symbolize?", answers: [], correnctAnswer: "Unity.", image: "", explanation: "" },
  {
    id: 44,
    question: "What did the Fathers of Confederation do?",
    answers: [],
    correnctAnswer: "They worked together to establish a new country, the Dominion of Canada",
    image: "",
    explanation: "",
  },
  { id: 45, question: "What do you call a law before it is passed?", answers: [], correnctAnswer: "A Bill.", image: "", explanation: "" },
  { id: 46, question: "What do you call the Sovereign’s representative in the provinces?", answers: [], correnctAnswer: "Lieutenant-Governor.", image: "", explanation: "" },
  { id: 47, question: "What do you mark on a federal election ballot?", answers: [], correnctAnswer: 'An "X".', image: "", explanation: "" },
  { id: 48, question: "What does Confederation mean?", answers: [], correnctAnswer: "Joining of provinces to make a new country.", image: "", explanation: "" },
  {
    id: 49,
    question: "What does it mean to say Canada is a constitutional monarchy?",
    answers: [],
    correnctAnswer: "Canada's Head of State is a hereditary Sovereign (Queen or King) who reigns in accordance with the Constitution.",
    image: "",
    explanation: "",
  },
  {
    id: 50,
    question: "What does the “right to a secret ballot” mean?",
    answers: [],
    correnctAnswer: "No one can watch your vote and no one should look at how you voted",
    image: "",
    explanation: "",
  },
  {
    id: 51,
    question: "What does the Canadian flag look like?",
    answers: [],
    correnctAnswer: "White with a red border on each end and a red maple leaf in the centre.",
    image: "",
    explanation: "",
  },
  {
    id: 52,
    question: "What does the term “responsible government” mean?",
    answers: [],
    correnctAnswer: "The ministers of the Crown must have the support of a majority of the elected representatives in order to govern.",
    image: "",
    explanation: "",
  },
  { id: 53, question: "What does the word “Inuit” mean?", answers: [], correnctAnswer: '"The people" in the Inuktitut language.', image: "", explanation: "" },
  {
    id: 54,
    question: "What happened at the Battle of the Plains of Abraham?",
    answers: [],
    correnctAnswer: "The British defeated the French marking the end of France's empire in America",
    image: "",
    explanation: "",
  },
  { id: 55, question: "What is a Francophone?", answers: [], correnctAnswer: "A person who speaks French as their first language", image: "", explanation: "" },
  { id: 56, question: "What is a major river in Quebec?", answers: [], correnctAnswer: "St. Lawrence River", image: "", explanation: "" },
  {
    id: 57,
    question: "What is a majority government?",
    answers: [],
    correnctAnswer: "When the party in power holds at least half of the seats in the House of Commons.",
    image: "",
    explanation: "",
  },
  { id: 58, question: "What is a voter information card?", answers: [], correnctAnswer: "A form that tells you when and where to vote.", image: "", explanation: "" },
  { id: 59, question: "What is Canada’s national winter sport?", answers: [], correnctAnswer: "Hockey.", image: "", explanation: "" },
  { id: 60, question: "What is Canada’s system of government called?", answers: [], correnctAnswer: "Parliamentary government.", image: "", explanation: "" },
  { id: 61, question: "What is meant by the equality of women and men?", answers: [], correnctAnswer: "Men and women are equal under the law.", image: "", explanation: "" },
  { id: 62, question: "What is the “head tax”?", answers: [], correnctAnswer: "Race-based entry fee charged for Chinese entering Canada.", image: "", explanation: "" },
  { id: 63, question: "What is the capital city of Canada?", answers: [], correnctAnswer: "Ottawa.", image: "", explanation: "" },
  {
    id: 64,
    question: "What is the difference between the role of the Sovereign and that of the Prime Minister?",
    answers: [],
    correnctAnswer: "The Sovereign is the guardian of Constitutional freedoms, the Prime Minister selects the Cabinet ministers and is responsible for operations and policy of government.",
    image: "",
    explanation: "",
  },
  { id: 65, question: "What is the government of all of Canada called?", answers: [], correnctAnswer: "Federal.", image: "", explanation: "" },
  { id: 66, question: "What is the highest court in Canada?", answers: [], correnctAnswer: "The Supreme Court of Canada", image: "", explanation: "" },
  { id: 67, question: "What is the highest military honour a Canadian can receive?", answers: [], correnctAnswer: "Victoria Cross.", image: "", explanation: "" },
  { id: 68, question: "What is the largest religious affiliation in Canada?", answers: [], correnctAnswer: "Catholic.", image: "", explanation: "" },
  {
    id: 69,
    question: "What is the meaning of the Remembrance Day poppy?",
    answers: [],
    correnctAnswer: "To remember the sacrifice of Canadians who have served or died in wars up to the present day.",
    image: "",
    explanation: "",
  },
  { id: 70, question: "What is the name of the Governor General?", answers: [], correnctAnswer: "Richard Wagner.", image: "", explanation: "" },
  {
    id: 71,
    question: "What is the name of the Prime Minister of Canada and his/her party?",
    answers: [],
    correnctAnswer: "Justin Trudeau (Liberal Party).",
    image: "",
    explanation: "",
  },
  { id: 72, question: "What is the name of the Royal Anthem of Canada?", answers: [], correnctAnswer: "God Save the Queen (or King).", image: "", explanation: "" },
  { id: 73, question: "What is the role of the courts in Canada?", answers: [], correnctAnswer: "To settle disputes.", image: "", explanation: "" },
  {
    id: 74,
    question: "What is the role of the Opposition parties?",
    answers: [],
    correnctAnswer: "To oppose or try to improve government proposals.",
    image: "",
    explanation: "",
  },
  {
    id: 75,
    question: "What is the significance of the discovery of insulin by Sir Frederick Banting and Charles Best?",
    answers: [],
    correnctAnswer: "Insulin has saved 16 million lives worldwide.",
    image: "",
    explanation: "",
  },
  {
    id: 76,
    question: "What part of the Constitution legally protects the basic rights and freedoms of all Canadians?",
    answers: [],
    correnctAnswer: "The Canadian Charter of Rights and Freedoms.",
    image: "",
    explanation: "",
  },
  { id: 77, question: "What percentage of Aboriginal people are First Nations?", answers: [], correnctAnswer: "65%.", image: "", explanation: "" },
  {
    id: 78,
    question: "What should you do if you do not receive a voter information card telling you when and where to vote?",
    answers: [],
    correnctAnswer: "Call Elections Canada or visit their website.",
    image: "",
    explanation: "",
  },
  { id: 79, question: "What song is Canada’s national anthem?", answers: [], correnctAnswer: "O Canada.", image: "", explanation: "" },
  { id: 80, question: "What three oceans border Canada?", answers: [], correnctAnswer: "Atlantic, Arctic and Pacific.", image: "", explanation: "" },
  {
    id: 81,
    question: "81. What was the “Underground Railroad”?",
    answers: [],
    correnctAnswer: "An anti-slavery network that helped thousands of slaves escape the United States and settle in Canada",
    image: "",
    explanation: "",
  },
  {
    id: 82,
    question: "What was the significance of June 6, 1944 invasion of Normandy?",
    answers: [],
    correnctAnswer: "Canadians made a significant contribution to the defeat of Nazism and Fascism in Europe during the Second World War.",
    image: "",
    explanation: "",
  },
  { id: 83, question: "What was the Women’s Suffrage Movement?", answers: [], correnctAnswer: "The effort by women to achieve the right to vote.", image: "", explanation: "" },
  {
    id: 84,
    question: "What will you promise when you take the Oath of Citizenship?",
    answers: [],
    correnctAnswer: "Pledge allegiance to the Queen, observe the laws of Canada and fulfil the duties of a Canadian.",
    image: "",
    explanation: "",
  },
  { id: 85, question: "What year did Newfoundland and Labrador join Canada?", answers: [], correnctAnswer: "1949", image: "", explanation: "" },
  { id: 86, question: "What year was Confederation?", answers: [], correnctAnswer: "1867.", image: "", explanation: "" },
  { id: 87, question: "When asked, who must you tell how you voted in a federal election?", answers: [], correnctAnswer: "No one.", image: "", explanation: "" },
  { id: 88, question: "When did the British North America Act come into effect?", answers: [], correnctAnswer: "1867.", image: "", explanation: "" },
  {
    id: 89,
    question: "When did the Canadian Charter of Rights and Freedoms become part of the Canadian Constitution?",
    answers: [],
    correnctAnswer: "1982.",
    image: "",
    explanation: "",
  },
  {
    id: 90,
    question: "When is Canada Day and what does it celebrate?",
    answers: [],
    correnctAnswer: "We celebrate the anniversary of Confederation July 1st of each year.",
    image: "",
    explanation: "",
  },
  { id: 91, question: "When is Remembrance Day celebrated?", answers: [], correnctAnswer: "November 11th.", image: "", explanation: "" },
  {
    id: 92,
    question: "When must federal elections be held?",
    answers: [],
    correnctAnswer: "On the third Monday in October every four years following the most recent general election.",
    image: "",
    explanation: "",
  },
  {
    id: 93,
    question: "When you vote on election day, what do you do?",
    answers: [],
    correnctAnswer:
      "Go to the voting station with your voter's card and ID, mark an X next to your chosen candidate, fold the ballot and present it to the poll officials who will tear off the ballot number and give you the ballot to deposit in the box",
    image: "",
    explanation: "",
  },
  { id: 94, question: "Where are the Great Lakes?", answers: [], correnctAnswer: "Between Ontario and the United States", image: "", explanation: "" },
  { id: 95, question: "Where are the Parliament Buildings located?", answers: [], correnctAnswer: "Ottawa.", image: "", explanation: "" },
  { id: 96, question: "Where do most French-speaking Canadians live?", answers: [], correnctAnswer: "Quebec.", image: "", explanation: "" },
  { id: 97, question: "Where does Canada rank in the world’s largest countries?", answers: [], correnctAnswer: "Second", image: "", explanation: "" },
  {
    id: 98,
    question: "Which Act granted, for the first time in Canada, legislative assemblies elected by the people?",
    answers: [],
    correnctAnswer: "The Constitutional Act of 1791.",
    image: "",
    explanation: "",
  },
  { id: 99, question: "Which animal is an official symbol of Canada?", answers: [], correnctAnswer: "The beaver.", image: "", explanation: "" },
  { id: 100, question: "Which country borders Canada on the south?", answers: [], correnctAnswer: "United States of America.", image: "", explanation: "" },
  { id: 101, question: "Which federal political party is in power?", answers: [], correnctAnswer: "Liberal Party.", image: "", explanation: "" },
  { id: 102, question: "Which of the following is NOT a feature of Canada’s system of government?", answers: [], correnctAnswer: "Dictatorship.", image: "", explanation: "" },
  {
    id: 103,
    question: "Which of the following sentences best describes the War of 1812?",
    answers: [],
    correnctAnswer: "The USA invaded Canada and was defeated, which ensured that Canada would remain independent of the United States.",
    image: "",
    explanation: "",
  },
  {
    id: 104,
    question: "Which of the following statements about residential schools is NOT true?",
    answers: [],
    correnctAnswer: "The schools were welcomed by the Aboriginal people.",
    image: "",
    explanation: "",
  },
  { id: 105, question: "Which party becomes the Official Opposition?", answers: [], correnctAnswer: "The party with the second most MPs.", image: "", explanation: "" },
  { id: 106, question: "Which party is the Official Opposition at the federal level?", answers: [], correnctAnswer: "The Conservative Party.", image: "", explanation: "" },
  { id: 107, question: "Which port is the largest and busiest in Canada?", answers: [], correnctAnswer: "The Port of Vancouver", image: "", explanation: "" },
  { id: 108, question: "Which province has its own time zone?", answers: [], correnctAnswer: "Newfoundland and Labrador", image: "", explanation: "" },
  { id: 109, question: "Which province in Canada is the smallest in land size?", answers: [], correnctAnswer: "Prince Edward Island.", image: "", explanation: "" },
  { id: 110, question: "Which province is the main producer of pulp and paper and hydro-electricity?", answers: [], correnctAnswer: "Quebec", image: "", explanation: "" },
  { id: 111, question: "Which province is the only officially bilingual province?", answers: [], correnctAnswer: "New Brunswick.", image: "", explanation: "" },
  { id: 112, question: "Which province was split into two at Confederation?", answers: [], correnctAnswer: "The Province of Canada", image: "", explanation: "" },
  { id: 113, question: "Which province was the first to grant voting rights to women?", answers: [], correnctAnswer: "Manitoba", image: "", explanation: "" },
  { id: 114, question: "Which provincial flag features the fleur-de-lys?", answers: [], correnctAnswer: "Quebec", image: "", explanation: "" },
  { id: 115, question: "Which region covers more than one-third of Canada?", answers: [], correnctAnswer: "Northern Territories.", image: "", explanation: "" },
  {
    id: 116,
    question: "Which region is known as the industrial and manufacturing heartland of Canada?",
    answers: [],
    correnctAnswer: "Central Canada.",
    image: "",
    explanation: "",
  },
  {
    id: 117,
    question: "Which region of Canada is known for both its fertile agricultural land and valuable energy resources?",
    answers: [],
    correnctAnswer: "Prairie provinces.",
    image: "",
    explanation: "",
  },
  { id: 118, question: "Which three countries are signatories to NAFTA?", answers: [], correnctAnswer: "Canada, Mexico and the United States.", image: "", explanation: "" },
  { id: 119, question: "Which was the last province to join Canada?", answers: [], correnctAnswer: "Newfoundland.", image: "", explanation: "" },
  { id: 120, question: "Who are the Aboriginal peoples of Canada?", answers: [], correnctAnswer: "The first people to live in Canada", image: "", explanation: "" },
  {
    id: 121,
    question: "Who are the Acadians?",
    answers: [],
    correnctAnswer: "The descendants of French colonists who began settling in what are now the Maritime provinces in 1604.",
    image: "",
    explanation: "",
  },
  { id: 122, question: "Who are the founding peoples of Canada?", answers: [], correnctAnswer: "Aboriginal, French and British.", image: "", explanation: "" },
  { id: 123, question: "Who are the Métis?", answers: [], correnctAnswer: "A distinct people of mixed Aboriginal and European ancestry.", image: "", explanation: "" },
  { id: 124, question: "Who are the Quebecers?", answers: [], correnctAnswer: "People of Quebec.", image: "", explanation: "" },
  {
    id: 125,
    question: "Who do Canadians vote for in a federal election?",
    answers: [],
    correnctAnswer: "A candidate they want to represent them in Parliament.",
    image: "",
    explanation: "",
  },
  {
    id: 126,
    question: "Who do Members of Parliament represent?",
    answers: [],
    correnctAnswer: "Everyone who lives in his or her electoral district.",
    image: "",
    explanation: "",
  },
  {
    id: 127,
    question: "Who had played an important part in building the Canadian Pacific Railway (CPR)?",
    answers: [],
    correnctAnswer: "Chinese railroad workers.",
    image: "",
    explanation: "",
  },
  {
    id: 128,
    question: "Who has the right to run as a candidate in federal elections?",
    answers: [],
    correnctAnswer: "Any Canadian citizen who is at least 18 years old.",
    image: "",
    explanation: "",
  },
  {
    id: 129,
    question: "Who has the right to vote in federal elections?",
    answers: [],
    correnctAnswer: "A Canadian citizen, 18 years or older, and on voters' list.",
    image: "",
    explanation: "",
  },
  { id: 130, question: "Who have major responsibilities on First Nations reserves?", answers: [], correnctAnswer: "Band chiefs and councillors.", image: "", explanation: "" },
  { id: 131, question: "Who is Canada’s Head of State?", answers: [], correnctAnswer: "Her Majesty Queen Elizabeth II.", image: "", explanation: "" },
  { id: 132, question: "Who is considered the father of Manitoba?", answers: [], correnctAnswer: "Louis Riel", image: "", explanation: "" },
  { id: 133, question: "Who is General Sir Arthur Currie?", answers: [], correnctAnswer: "Canada's greatest soldier in the First World War.", image: "", explanation: "" },
  { id: 134, question: "Who is the Head of Government?", answers: [], correnctAnswer: "The Prime Minister", image: "", explanation: "" },
  { id: 135, question: "Who is the leader of the Federal Official Opposition Party?", answers: [], correnctAnswer: "Erin O'Toole", image: "", explanation: "" },
  { id: 136, question: "Who is the Queen’s representative in Canada?", answers: [], correnctAnswer: "Governor General of Canada.", image: "", explanation: "" },
  { id: 137, question: "Who led an armed uprising and seized Fort Garry?", answers: [], correnctAnswer: "Louis Riel", image: "", explanation: "" },
  { id: 138, question: "Who led Quebec into Confederation?", answers: [], correnctAnswer: "Sir George-Étienne Cartier", image: "", explanation: "" },
  {
    id: 139,
    question: "Who was Sir Louis-Hippolyte La Fontaine?",
    answers: [],
    correnctAnswer: "A champion of democracy and French language rights and the first leader of a responsible government in the Canadas.",
    image: "",
    explanation: "",
  },
  { id: 140, question: "Who was Sir Sam Steele?", answers: [], correnctAnswer: "A great frontier hero, Mounted Policeman and soldier of the Queen.", image: "", explanation: "" },
  {
    id: 141,
    question: "Who was the first leader of a responsible government in the Canadas in 1849?",
    answers: [],
    correnctAnswer: "Sir Louis-Hippolyte La Fontaine.",
    image: "",
    explanation: "",
  },
  { id: 142, question: "Who was the first Prime Minister of Canada?", answers: [], correnctAnswer: "Sir John A. Macdonald.", image: "", explanation: "" },
  {
    id: 143,
    question: "Who were the United Empire Loyalists?",
    answers: [],
    correnctAnswer: "Settlers who came to Canada from the United States during the American Revolution.",
    image: "",
    explanation: "",
  },
  { id: 144, question: "Who were the Voyagers?", answers: [], correnctAnswer: "Montreal-based traders who travelled by canoe", image: "", explanation: "" },
  {
    id: 145,
    question: "Why is the battle of Vimy Ridge important?",
    answers: [],
    correnctAnswer: "Canadian Corps secured its reputation for valour and bravery.",
    image: "",
    explanation: "",
  },
  {
    id: 146,
    question: "Why is trade with other countries important to Canada?",
    answers: [],
    correnctAnswer: "It enhances our economy and raises our standard of living.",
    image: "",
    explanation: "",
  },
  { id: 147, question: "What is the name of the Lieutenant-Governor of Quebec?", answers: [], correnctAnswer: "Honourable J. Michel Doyon", image: "", explanation: "" },
  { id: 148, question: "What is the capital city of Alberta?", answers: [], correnctAnswer: "Edmonton.", image: "", explanation: "" },
  { id: 149, question: "What is the name of the leader of the Opposition in Alberta?", answers: [], correnctAnswer: "Rachel Notley.", image: "", explanation: "" },
  { id: 150, question: "What is the name of the Lieutenant-Governor of Alberta?", answers: [], correnctAnswer: "Salma Lakhani.", image: "", explanation: "" },
  { id: 151, question: "What is the name of the Premier of Alberta?", answers: [], correnctAnswer: "Premier Jason Kenney.", image: "", explanation: "" },
  { id: 152, question: "Which political party is in power in Alberta?", answers: [], correnctAnswer: "United Conservative Party", image: "", explanation: "" },
  {
    id: 153,
    question: "Which three natural resources are important to Alberta’s economy today?",
    answers: [],
    correnctAnswer: "Oil, agriculture, and forestry.",
    image: "",
    explanation: "",
  },
  {
    id: 154,
    question: "Name the federal electoral districts in Richmond, British Columbia.",
    answers: [],
    correnctAnswer: "Richmond has two federal electoral districts: Richmond Centre and Steveston-Richmond East",
    image: "",
    explanation: "",
  },
  {
    id: 155,
    question: "Name the members of Parliament for Richmond, British Columbia and the parties they belong to (Richmond Centre, Steveston-Richmond East respectively).",
    answers: [],
    correnctAnswer: "Alice Wong (Conservative), Kenny Chiu (Conservative)",
    image: "",
    explanation: "",
  },
  {
    id: 156,
    question:
      "Name the Members of the Legislative Assembly for Richmond, British Columbia and the parties they belong to (Richmond North Centre, Richmond South Centre, Richmond-Steveston, and Richmond-Queensborough respectively).",
    answers: [],
    correnctAnswer: "Teresa Wat (Richmond North Centre), Henry Yao (Richmond South Centre), Kelly Greene(Richmond-Steveston), Aman Singh (Richmond-Queensborough).",
    image: "",
    explanation: "",
  },
  {
    id: 157,
    question: "Name three city councillors for Richmond, British Columbia.",
    answers: [],
    correnctAnswer: "Harold Steves, Chak Au and Carol Day",
    image: "",
    explanation: "",
  },
  { id: 158, question: "What is the capital city of British Columbia?", answers: [], correnctAnswer: "Victoria.", image: "", explanation: "" },
  { id: 159, question: "What is the name of the leader of the Opposition in British Columbia?", answers: [], correnctAnswer: "Shirley Bond", image: "", explanation: "" },
  { id: 160, question: "What is the name of the Lieutenant-Governor of British Columbia?", answers: [], correnctAnswer: "Janet Austin", image: "", explanation: "" },
  { id: 161, question: "What is the name of the Mayor of Richmond, British Columbia?", answers: [], correnctAnswer: "Mayor Malcolm Brodie", image: "", explanation: "" },
  { id: 162, question: "What is the name of the Premier of British Columbia?", answers: [], correnctAnswer: "Premier John Horgan", image: "", explanation: "" },
  { id: 163, question: "Which political party is in power in British Columbia?", answers: [], correnctAnswer: "New Democratic Party", image: "", explanation: "" },
  {
    id: 164,
    question: "Which three natural resources are important to British Columbia’s economy today?",
    answers: [],
    correnctAnswer: "Forests, fish and water.",
    image: "",
    explanation: "",
  },
  {
    id: 165,
    question: "Why is British Columbia known as Canada’s Pacific Gateway?",
    answers: [],
    correnctAnswer: "Billions of dollars in trade goods are handled through the Port of Vancouver.",
    image: "",
    explanation: "",
  },
  { id: 166, question: "What is the capital city of Manitoba?", answers: [], correnctAnswer: "Winnipeg", image: "", explanation: "" },
  { id: 167, question: "What is the name of the leader of the Opposition in Manitoba?", answers: [], correnctAnswer: "Wab Kinew", image: "", explanation: "" },
  { id: 168, question: "What is the name of the Lieutenant-Governor of Manitoba?", answers: [], correnctAnswer: "Honourable Janice Filmon", image: "", explanation: "" },
  { id: 169, question: "What is the name of the Premier of Manitoba?", answers: [], correnctAnswer: "Premier Brian Pallister", image: "", explanation: "" },
  {
    id: 170,
    question: "What three industries are important to Manitoba’s economy today?",
    answers: [],
    correnctAnswer: "Agriculture, mining and hydro-electric power generation",
    image: "",
    explanation: "",
  },
  { id: 171, question: "Which political party is in power in Manitoba?", answers: [], correnctAnswer: "Progressive Conservative", image: "", explanation: "" },
  { id: 172, question: "What is the capital city of New Brunswick?", answers: [], correnctAnswer: "Fredericton", image: "", explanation: "" },
  { id: 173, question: "What is the name of the leader of the Opposition in New Brunswick?", answers: [], correnctAnswer: "Roger Melanson", image: "", explanation: "" },
  { id: 174, question: "What is the name of the Lieutenant-Governor of New Brunswick?", answers: [], correnctAnswer: "Honourable Brenda Murphy", image: "", explanation: "" },
  { id: 175, question: "What is the name of the Premier of New Brunswick?", answers: [], correnctAnswer: "Premier Blaine Higgs", image: "", explanation: "" },
  {
    id: 176,
    question: "What three industries are important to New Brunswick’s economy today?",
    answers: [],
    correnctAnswer: "Forestry, agriculture and mining",
    image: "",
    explanation: "",
  },
  { id: 177, question: "Which political party is in power in New Brunswick?", answers: [], correnctAnswer: "Progressive Conservative", image: "", explanation: "" },
  { id: 178, question: "What is the capital city of Newfoundland and Labrador?", answers: [], correnctAnswer: "St. John's", image: "", explanation: "" },
  {
    id: 179,
    question: "What is the name of the leader of the Opposition in Newfoundland and Labrador?",
    answers: [],
    correnctAnswer: "Ches Crosbie",
    image: "",
    explanation: "",
  },
  {
    id: 180,
    question: "What is the name of the Lieutenant-Governor of Newfoundland and Labrador?",
    answers: [],
    correnctAnswer: "Honourable Judy May Foote",
    image: "",
    explanation: "",
  },
  { id: 181, question: "181. What is the name of the Premier of Newfoundland and Labrador?", answers: [], correnctAnswer: "Premier Andrew Furey", image: "", explanation: "" },
  {
    id: 182,
    question: "What three industries are important to Newfoundland and Labrador’s economy today?",
    answers: [],
    correnctAnswer: "Fisheries, oil and gas extraction",
    image: "",
    explanation: "",
  },
  { id: 183, question: "Which political party is in power in Newfoundland and Labrador?", answers: [], correnctAnswer: "Liberal Party", image: "", explanation: "" },
  { id: 184, question: "What is the capital City of Nova Scotia?", answers: [], correnctAnswer: "Halifax", image: "", explanation: "" },
  { id: 185, question: "What is the name of the leader of the Opposition in Nova Scotia?", answers: [], correnctAnswer: "Tim Houston", image: "", explanation: "" },
  { id: 186, question: "What is the name of the Lieutenant-Governor of Nova Scotia?", answers: [], correnctAnswer: "Honourable Arthur J. LeBlanc", image: "", explanation: "" },
  { id: 187, question: "What is the name of the Premier of Nova Scotia?", answers: [], correnctAnswer: "Premier Iain Rankin", image: "", explanation: "" },
  {
    id: 188,
    question: "What three industries are important to Nova Scotia’s economy today?",
    answers: [],
    correnctAnswer: "Coal mining, forestry and agriculture",
    image: "",
    explanation: "",
  },
  { id: 189, question: "Which political party is in power in Nova Scotia?", answers: [], correnctAnswer: "Liberal", image: "", explanation: "" },
  { id: 190, question: "What is the capital City of the Northwest Territories?", answers: [], correnctAnswer: "Yellowknife", image: "", explanation: "" },
  {
    id: 191,
    question: "What is the name of the Commissioner of the Northwest Territories?",
    answers: [],
    correnctAnswer: "Honourable Margaret Thom",
    image: "",
    explanation: "",
  },
  { id: 192, question: "What is the name of the leader of the Opposition in the Northwest Territories?", answers: [], correnctAnswer: "None", image: "", explanation: "" },
  { id: 193, question: "What is the name of the Premier of the Northwest Territories?", answers: [], correnctAnswer: "Premier Caroline Cochrane", image: "", explanation: "" },
  { id: 194, question: "Which political party is in power in the Northwest Territories?", answers: [], correnctAnswer: "Governed by consensus", image: "", explanation: "" },
  { id: 195, question: "What is the capital City of the Nunavut?", answers: [], correnctAnswer: "Iqaluit", image: "", explanation: "" },
  { id: 196, question: "What is the name of the Commissioner of Nunavut?", answers: [], correnctAnswer: "Honourable Nellie Taptaqut Kusugak", image: "", explanation: "" },
  { id: 197, question: "What is the name of the leader of the Opposition in Nunavut?", answers: [], correnctAnswer: "None", image: "", explanation: "" },
  { id: 198, question: "What is the name of the Premier of Nunavut?", answers: [], correnctAnswer: "Premier Joe Savikataaq", image: "", explanation: "" },
  { id: 199, question: "Which political party is in power in Nunavut?", answers: [], correnctAnswer: "Governed by consensus", image: "", explanation: "" },
  { id: 200, question: "What is the capital city of Ontario?", answers: [], correnctAnswer: "Toronto", image: "", explanation: "" },
  { id: 201, question: "What is the name of the leader of the Opposition in Ontario?", answers: [], correnctAnswer: "Andrea Horwath", image: "", explanation: "" },
  { id: 202, question: "What is the name of the Lieutenant-Governor of Ontario?", answers: [], correnctAnswer: "Elizabeth Dowdeswell", image: "", explanation: "" },
  { id: 203, question: "What is the name of the Premier of Ontario?", answers: [], correnctAnswer: "Premier Doug Ford", image: "", explanation: "" },
  {
    id: 204,
    question: "What three industries are important to Ontario’s economy today?",
    answers: [],
    correnctAnswer: "Mining, tourism, automobile manufacturing",
    image: "",
    explanation: "",
  },
  { id: 205, question: "Which political party is in power in Ontario?", answers: [], correnctAnswer: "Progressive Conservative Party", image: "", explanation: "" },
  {
    id: 206,
    question: "Which three are Members of Ontario’s Legislative Assembly?",
    answers: [],
    correnctAnswer: "Rod Phillips, Todd Smith, Michael Coteau",
    image: "",
    explanation: "",
  },
  {
    id: 207,
    question: "Which three are members of Parliament for Ottawa, Ontario?",
    answers: [],
    correnctAnswer: "David McGuinty, Mona Fortier, Catherine McKenna",
    image: "",
    explanation: "",
  },
  { id: 208, question: "What is the capital City of the Prince Edward Island?", answers: [], correnctAnswer: "Charlottetown", image: "", explanation: "" },
  {
    id: 209,
    question: "What is the name of the leader of the Opposition in Prince Edward Island?",
    answers: [],
    correnctAnswer: "Peter Bevan-Baker",
    image: "",
    explanation: "",
  },
  {
    id: 210,
    question: "What is the name of the Lieutenant-Governor of Prince Edward Island?",
    answers: [],
    correnctAnswer: "Honourable Antoinette Perry",
    image: "",
    explanation: "",
  },
  { id: 211, question: "What is the name of the Premier of Prince Edward Island?", answers: [], correnctAnswer: "Premier Dennis King", image: "", explanation: "" },
  { id: 212, question: "Which political party is in power in Prince Edward Island?", answers: [], correnctAnswer: "Progressive Conservative", image: "", explanation: "" },
  { id: 213, question: "What is the capital City of the Quebec?", answers: [], correnctAnswer: "Quebec City", image: "", explanation: "" },
  { id: 214, question: "What is the name of the leader of the Opposition in Quebec?", answers: [], correnctAnswer: "Dominique Anglade", image: "", explanation: "" },
  { id: 215, question: "What is the name of the Premier of Quebec ?", answers: [], correnctAnswer: "Premier Francois Legault", image: "", explanation: "" },
  {
    id: 216,
    question: "What three industries are important to Quebec’s economy today?",
    answers: [],
    correnctAnswer: "Pulp and paper, forestry and hydro-electric power",
    image: "",
    explanation: "",
  },
  { id: 217, question: "Which political party is in power in Quebec?", answers: [], correnctAnswer: "Coalition Avenir Québec", image: "", explanation: "" },
  { id: 218, question: "What is the capital city of Saskatchewan?", answers: [], correnctAnswer: "Regina", image: "", explanation: "" },
  { id: 219, question: "What is the name of the leader of the Opposition in Saskatchewan?", answers: [], correnctAnswer: "Ryan Meili", image: "", explanation: "" },
  { id: 220, question: "What is the name of the Lieutenant-Governor of Saskatchewan?", answers: [], correnctAnswer: "Honourable Russ Mirasty", image: "", explanation: "" },
  { id: 221, question: "What is the name of the Premier of Saskatchewan?", answers: [], correnctAnswer: "Premier Scott Moe", image: "", explanation: "" },
  {
    id: 222,
    question: "What three industries are important to Saskatchewan’s economy today?",
    answers: [],
    correnctAnswer: "Farming, mining and natural gas",
    image: "",
    explanation: "",
  },
  { id: 223, question: "Which political party is in power in Saskatchewan?", answers: [], correnctAnswer: "Saskatchewan Party", image: "", explanation: "" },
  { id: 224, question: "What is the capital city of Yukon Territory?", answers: [], correnctAnswer: "Whitehorse", image: "", explanation: "" },
  { id: 225, question: "What is the name of the Commissioner of Yukon Territory?", answers: [], correnctAnswer: "Honourable Angélique Bernard", image: "", explanation: "" },
  { id: 226, question: "What is the name of the leader of the Opposition in Yukon Territory?", answers: [], correnctAnswer: "Stacey Hassard", image: "", explanation: "" },
  { id: 227, question: "What is the name of the Premier of Yukon Territory?", answers: [], correnctAnswer: "Premier Sandy Silver", image: "", explanation: "" },
  { id: 228, question: "Which political party is in power in Yukon Territory?", answers: [], correnctAnswer: "Liberal", image: "", explanation: "" },
];

export default all_questions;
